name: CI

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  ssh-connect:
    runs-on: ubuntu-latest
    
    steps:
      - name: Greeting
        run: echo Start unit tests

      - name: Farewell
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
